insta - fix attribute error in build
AttributeError: 'NoneType' object has no attribute 'rstrip'
caused by defaulting INSTA env var to None instead of empty string